# Site settings
title: "Optimal Coder"
description: "description"
author: "Mirnes Mrkaljevic"
baseurl: "/docs"  # Set this to "/blog" if your blog is in a subfolder
url: "https://mirnes-mrkaljevic.github.io"

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from Jekyll build (optional)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
