# Site settings
title: "Optimal Coder"
description: "description"
author: "Mirnes Mrkaljevic"
baseurl: ""  # Set this to "/blog" if your blog is in a subfolder
url: "https://mirnes-mrkaljevic.github.io"

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0

paginate: 5
paginate_path: "/page:num/"


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate


# Exclude files from Jekyll build (optional)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
