# Site settings
title: "Optimal Coder"
description: "description"
author: "Mirnes Mrkaljevic"
baseurl: "/docs"  # Set this to "/blog" if your blog is in a subfolder
url: "https://mirnes-mrkaljevic.github.io"

# Theme settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from Jekyll build (optional)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
