# Site settings
title: "My Blog"
description: "A blog powered by GitHub Pages with the Cayman theme"
author: "Mirnes Mrkaljevic"
baseurl: "/docs"  # Set this to "/blog" if your blog is in a subfolder
url: "https://mirnes-mrkaljevic.github.io"

# Theme settings
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from Jekyll build (optional)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
