theme: jekyll-theme-cayman
title: Optimal Coder
description: Optimal Coder
lsi: false
safe: true
source: /site
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
