name: Daily Build for GitHub Pages

on:
  schedule:
    - cron: "0 0 * * *"  # This runs at midnight UTC every day
  workflow_dispatch:  # This allows you to trigger the build manually if needed

jobs:
  build:
    runs-on: ubuntu-latest  # Choose the OS for the action to run on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository code

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8 # Specify your Ruby version if needed

      - name: Install dependencies
        run: |
          gem install bundler
          cd docs  # Change directory to docs folder
          bundle install  # Install dependencies from the Gemfile in docs folder

      - name: Build site (just to test, not to deploy)
        run: |
          cd docs
          bundle exec jekyll build