name: Daily Build for GitHub Pages

on:
  schedule:
    - cron: "0 0 * * *"  # This runs at midnight UTC every day
  workflow_dispatch:  # This allows you to trigger the build manually if needed

jobs:
  build:
    runs-on: ubuntu-latest  # Choose the OS for the action to run on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository code

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8 # Specify your Ruby version if needed

      - name: Install dependencies
        run: |
          gem install bundler
          cd docs  # Change directory to docs folder
          bundle install  # Install dependencies from the Gemfile in docs folder

      - name: Build the site
        run: |
          cd docs  # Ensure we're in the docs folder
          bundle exec jekyll build --destination ./docs  # Build the site into the docs folder

      - name: Deploy to GitHub Pages
        run: |
          bundle exec jekyll build  --destination ./docs
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add -A
          git commit -m "Daily build update"
          git push origin main  # Make sure your default branch is correct
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
